/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sistemasoperativos.productor_consumidor.Vista;

import com.sistemasoperativos.productor_consumidor.Instrucciones.Hilo_Entregar_Pedidos;
import com.sistemasoperativos.productor_consumidor.Instrucciones.Hilo_Hacer_Pedidos;
import com.sistemasoperativos.productor_consumidor.Instrucciones.Hilo_Pendientes_Cocinar;
import com.sistemasoperativos.productor_consumidor.Instrucciones.Buffer_General;
import com.sistemasoperativos.productor_consumidor.Instrucciones.Dibujar;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.Semaphore;

/**
 *
 * @author julioaguilar
 */
public class Vista_Principal extends javax.swing.JFrame implements ActionListener{

    private int x,y,fijox,fijoy;
    private Dibujar dibujar=new Dibujar();
    /**
     * Creates new form Vista_Principal
     */
    public Vista_Principal() {
        initComponents();
        this.add(dibujar,BorderLayout.CENTER);
        fijox=imagen_cocinero.getX();
        fijoy=imagen_cocinero.getY();
        btnDetener.addActionListener(this);
        btnEmpezar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetener = new javax.swing.JButton();
        btnEmpezar = new javax.swing.JButton();
        imagen_cocinero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnDetener.setText("Detener");
        getContentPane().add(btnDetener);
        btnDetener.setBounds(410, 180, 110, 24);

        btnEmpezar.setText("Empezar");
        getContentPane().add(btnEmpezar);
        btnEmpezar.setBounds(410, 130, 100, 24);

        imagen_cocinero.setIcon(new javax.swing.ImageIcon("/home/julioaguilar/NetBeansProjects/Hilos/src/main/java/com/sistemasoperativos/productor_consumidor/Vista/entregando.png")); // NOI18N
        imagen_cocinero.setText("jLabel1");
        getContentPane().add(imagen_cocinero);
        imagen_cocinero.setBounds(140, 90, 240, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JLabel imagen_cocinero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btnDetener){
            Buffer_General.iterar=false;
        }
        if (e.getSource()==btnEmpezar){
            Buffer_General.iterar=true;
            empezar();
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    public void empezar(){
        Semaphore semaforo=new Semaphore(1);
        //final Procesos proceso=new Procesos(semaforo);
        Hilo_Hacer_Pedidos hilo_pedidos=new Hilo_Hacer_Pedidos(semaforo, this);
        Hilo_Pendientes_Cocinar hilo_cocinar=new Hilo_Pendientes_Cocinar(semaforo);
        Hilo_Entregar_Pedidos hilo_entregar=new Hilo_Entregar_Pedidos(semaforo);
        hilo_pedidos.start();
        hilo_cocinar.start();
        hilo_entregar.start();
    }
    
    public void mover_cocinero_iz(){
        x=fijox;
        y=fijoy;
        imagen_cocinero.setLocation(x+2, y);
    }
    public void mover_cocinero_der(){
        x=fijox;
        y=fijoy;
        imagen_cocinero.setLocation(x-2, y);
    }
}
